# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_HistogramMode_5(x)
#'
DN_HistogramMode_5 <- function(x) {
    .Call('_catch22_DN_HistogramMode_5', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_HistogramMode_10(x)
#'
DN_HistogramMode_10 <- function(x) {
    .Call('_catch22_DN_HistogramMode_10', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_f1ecac(x)
#'
CO_f1ecac <- function(x) {
    .Call('_catch22_CO_f1ecac', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_FirstMin_ac(x)
#'
CO_FirstMin_ac <- function(x) {
    .Call('_catch22_CO_FirstMin_ac', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_HistogramAMI_even_2_5(x)
#'
CO_HistogramAMI_even_2_5 <- function(x) {
    .Call('_catch22_CO_HistogramAMI_even_2_5', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_trev_1_num(x)
#'
CO_trev_1_num <- function(x) {
    .Call('_catch22_CO_trev_1_num', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- MD_hrv_classic_pnn40(x)
#'
MD_hrv_classic_pnn40 <- function(x) {
    .Call('_catch22_MD_hrv_classic_pnn40', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SB_BinaryStats_mean_longstretch1(x)
#'
SB_BinaryStats_mean_longstretch1 <- function(x) {
    .Call('_catch22_SB_BinaryStats_mean_longstretch1', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SB_TransitionMatrix_3ac_sumdiagcov(x)
#'
SB_TransitionMatrix_3ac_sumdiagcov <- function(x) {
    .Call('_catch22_SB_TransitionMatrix_3ac_sumdiagcov', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- PD_PeriodicityWang_th0_01(x)
#'
PD_PeriodicityWang_th0_01 <- function(x) {
    .Call('_catch22_PD_PeriodicityWang_th0_01', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_Embed2_Dist_tau_d_expfit_meandiff(x)
#'
CO_Embed2_Dist_tau_d_expfit_meandiff <- function(x) {
    .Call('_catch22_CO_Embed2_Dist_tau_d_expfit_meandiff', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- IN_AutoMutualInfoStats_40_gaussian_fmmi(x)
#'
IN_AutoMutualInfoStats_40_gaussian_fmmi <- function(x) {
    .Call('_catch22_IN_AutoMutualInfoStats_40_gaussian_fmmi', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- FC_LocalSimple_mean1_tauresrat(x)
#'
FC_LocalSimple_mean1_tauresrat <- function(x) {
    .Call('_catch22_FC_LocalSimple_mean1_tauresrat', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_OutlierInclude_p_001_mdrmd(x)
#'
DN_OutlierInclude_p_001_mdrmd <- function(x) {
    .Call('_catch22_DN_OutlierInclude_p_001_mdrmd', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_OutlierInclude_n_001_mdrmd(x)
#'
DN_OutlierInclude_n_001_mdrmd <- function(x) {
    .Call('_catch22_DN_OutlierInclude_n_001_mdrmd', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SP_Summaries_welch_rect_area_5_1(x)
#'
SP_Summaries_welch_rect_area_5_1 <- function(x) {
    .Call('_catch22_SP_Summaries_welch_rect_area_5_1', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SB_BinaryStats_diff_longstretch0(x)
#'
SB_BinaryStats_diff_longstretch0 <- function(x) {
    .Call('_catch22_SB_BinaryStats_diff_longstretch0', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SB_MotifThree_quantile_hh(x)
#'
SB_MotifThree_quantile_hh <- function(x) {
    .Call('_catch22_SB_MotifThree_quantile_hh', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1(x)
#'
SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1 <- function(x) {
    .Call('_catch22_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1(x)
#'
SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1 <- function(x) {
    .Call('_catch22_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SP_Summaries_welch_rect_centroid(x)
#'
SP_Summaries_welch_rect_centroid <- function(x) {
    .Call('_catch22_SP_Summaries_welch_rect_centroid', PACKAGE = 'catch22', x)
}

#' Function to calculate a statistical feature
#'
#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- FC_LocalSimple_mean3_stderr(x)
#'
FC_LocalSimple_mean3_stderr <- function(x) {
    .Call('_catch22_FC_LocalSimple_mean3_stderr', PACKAGE = 'catch22', x)
}

#' This function rescales a vector of numerical values into the unit interval
#' [0,1] using a C++ implementation for efficiency.
#'
#' @param x a numeric vector, preferably of feature values computed by other catchEmAll package functions
#' @return x a numeric vector, rescaled into the [0,1] unit interval
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- minmax_scaler(x)
#'
minmax_scaler <- function(x) {
    .Call('_catch22_minmax_scaler', PACKAGE = 'catch22', x)
}

#' This function rescales a vector of numerical values into z-scores using a C++
#' implementation for efficiency.
#'
#' @param x a numeric vector, preferably of feature values computed by other catchEmAll package functions
#' @return x a numeric vector, rescaled into z-score range
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- zscore_scaler(x)
#'
zscore_scaler <- function(x) {
    .Call('_catch22_zscore_scaler', PACKAGE = 'catch22', x)
}

#' This function rescales a vector of numerical values with a Sigmoidal transformation
#' using a C++ implementation for efficiency.
#'
#' @param x a numeric vector, preferably of feature values computed by other catchEmAll package functions
#' @return x a numeric vector, rescaled into Sigmoidal range
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- sigmoid_scaler(x)
#'
sigmoid_scaler <- function(x) {
    .Call('_catch22_sigmoid_scaler', PACKAGE = 'catch22', x)
}

#' This function rescales a vector of numerical values with an outlier-robust
#' Sigmoidal transformation using a C++ implementation for efficiency.
#'
#' @param x a numeric vector, preferably of feature values computed by other catchEmAll package functions
#' @return x a numeric vector, rescaled into Sigmoidal range
#' @author Trent Henderson
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- robustsigmoid_scaler(x)
#'
robustsigmoid_scaler <- function(x) {
    .Call('_catch22_robustsigmoid_scaler', PACKAGE = 'catch22', x)
}

#' This function rescales a vector of numerical values by subtracting the mean using a C++
#' implementation for efficiency.
#'
#' @param x a numeric vector, preferably of feature values computed by other catchEmAll package functions
#' @return x a numeric vector, rescaled into x-mean range
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- mean_scaler(x)
#'
mean_scaler <- function(x) {
    .Call('_catch22_mean_scaler', PACKAGE = 'catch22', x)
}

